---
- name: Ensure Alertmanager is installed
  apt:
    name: prometheus-alertmanager
    state: present
  become: yes

# 确保 Alertmanager 配置文件所在的目录存在
- name: Ensure Alertmanager configuration directory exists
  file:
    path: "{{ alertmanager_config_file | dirname }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

# 部署 Alertmanager 配置文件
- name: Deploy Alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_file }}"
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: yes
  notify:
    - Restart Alertmanager

# 确保 Alertmanager 服务启用并运行
- name: Ensure Alertmanager service is enabled and running
  systemd:
    name: prometheus-alertmanager
    state: started
    enabled: true

# 确保 Prometheus 规则目录存在
- name: Ensure Prometheus rules directory exists
  file:
    path: /etc/prometheus/rules
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  become: yes

# 部署 Prometheus Alert Rules 配置
- name: Deploy Prometheus alert rules file
  copy:
    src: files/alert.rules.yml
    dest: /etc/prometheus/rules/alert.rules.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  become: yes
  notify: Restart Prometheus

# 确保 Prometheus 主配置中引用了规则文件
- name: Ensure Prometheus main configuration includes alert rules
  blockinfile:
    path: /etc/prometheus/prometheus.yml
    marker: "# {mark} PROMETHEUS ALERT RULES"
    insertbefore: '^scrape_configs:'
    block: |
      rule_files:
        - "/etc/prometheus/rules/alert.rules.yml"
  become: yes
  notify: Restart Prometheus

# 验证 Prometheus 配置文件
- name: Validate Prometheus configuration
  command: promtool check config /etc/prometheus/prometheus.yml
  register: promtool_check
  failed_when: "'FAILED' in promtool_check.stdout"
  changed_when: false
  become: yes
