---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create instance config
      when: server is defined and server.changed | default(false)
      block:
        - name: Populate instance config dict
          ansible.builtin.set_fact:
            instance_conf_dict:
              instance: "{{ item.name }}"
              address: "{{ item.address }}"
              user: "{{ item.user }}"
              port: "{{ item.port | default(22) }}"
              identity_file: "{{ item.identity_file }}"
          loop: "{{ server.results }}"
          register: instance_config_dict

        - name: Convert instance config dict to a list
          ansible.builtin.set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          ansible.builtin.copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_yaml }}
            dest: "{{ molecule_instance_config }}"
            mode: "0600"
