---
- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Validate and reload Nginx
  ansible.builtin.command:
    cmd: nginx -t && systemctl reload nginx
  notify:
    - reload nginx
