---
- name: Install and configure OpenVPN
  hosts: all
  become: yes
  vars:
    openvpn_port: 1194
    openvpn_protocol: udp
    openvpn_network: 10.8.0.0
    openvpn_mask: 255.255.255.0
  roles:
    - role: openvpn
